# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3c2a7418492562a64397b17ac9596654"
name = "Dry Hood mapa playas v1"
handle = "dry-hood-mapa-playas-v1"
application_url = "https://approximately-silence-competition-turning.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
dev_store_url = "dryhood-qa.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_content,write_online_store_pages"

[auth]
redirect_urls = [
  "https://approximately-silence-competition-turning.trycloudflare.com/auth/callback",
  "https://approximately-silence-competition-turning.trycloudflare.com/auth/shopify/callback",
  "https://approximately-silence-competition-turning.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
